apiVersion: v1
entries:
  opsgenie-heartbeat:
  - apiVersion: v1
    created: 2021-07-29T05:13:31.268390774Z
    description: opsgenie heartbeat for prometheus monitoring
    digest: 8868fdbe3b616a2f2461515060dd3ab38dd18d31d756c873fdb752205df84107
    name: opsgenie-heartbeat
    urls:
    - https://raw.githubusercontent.com/shalb/opsgenie-heartbeat/master/charts/opsgenie-heartbeat-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v1
    created: 2021-07-29T05:13:31.2680726Z
    description: opsgenie heartbeat for prometheus monitoring
    digest: 39ad8cb73ecbf769de06483a5913d7ff87750b23604af1f2d56fe8c819b0984c
    name: opsgenie-heartbeat
    urls:
    - https://raw.githubusercontent.com/shalb/opsgenie-heartbeat/master/charts/opsgenie-heartbeat-0.0.1.tgz
    version: 0.0.1
generated: 2021-07-29T05:13:31.257342356Z
